# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d715c5db9f228427ed3355e6eed872b1622297ee00a993875ff1ed2f84cd00a411e127532f97c45d8c90225ed770144c111fc1d9b406000bf11661ce3bdb1703

test:
  secret_key_base: a85ee74b3b496fd4967c209d8c5966f78e9a4ea7d3d954176a05efcf23e9d4323f7c11bb113277413ccdf1dbfcdc1a53b03bebab4b173df5f392058cd2248177

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
